/* 
    accounts template for assets
*/

// export function AccInit(id, name, acc_type, acc_subtype, acc_group, bal_side){
//     const idString = id.toString();
    
//     return {
//         account_id : id,
//         account_name : name, 
//         account_type : acc_type, 
//         account_subtype : acc_subtype,
//         account_group : acc_group,
//         balance_side : bal_side,
//         status : 'active',
//         open_credit : 0,
//         open_debit : 0,
//         open_balance : 0,
//         close_credit : 0,
//         close_debit : 0,
//         close_balance :0,
//         tags : []
//     }
// };

// export let cash = AccInit(
//     11101, 'cash' 
// );

// console.log(cash)

// export let available_for_sale_securities = AccInit(11201, "sekuritas tersedia untuk dijual", "aset", "aset lancar")
// export let available_for_sale_securities = {
//     account_id : 11201,
//     account_name : "sekuritas tersedia untuk dijual",
//     account_type : "aset",
//     account_subtype : "aset lancar",
//     account_group : "sekuritas",
//     balance_side : "debit",
//     status : 'active',
//     open_credit : 0,
//     open_debit : 0,
//     open_balance : 0,
//     close_credit : 0,
//     close_debit : 0,
//     close_balance : 0,
//     tags : []
// };

user_data = {
    id : null, //UID from the firebase auth
    email: "", // email from the firebase auth
    country: "", // user residence country
    phone: "+xx-xxx-xxxx-xxx", // I want to check if this is phone format
    address: "", // user address
    tax_id : "xx.xxx.xxx-xxx.xxx", // x is number digits I want the tax id to be formatted this way
};

book_data = {
    id : "", // combination of: user_id-book_num in string
    id_set : {
        user_id : null, // user id from auth
        book_num : null // book incremented numbering
    },
    user_name: "", // name of the company or personal user using this book
    user_code: "", // Three letters to represent user
    user_type: "", // PT, CV, Firm, UD or personal
    start_date: new Date(), // Date which the book is created (using ),
    business_type: "", // short description on what kind of business to record (manufacture, finance, invest, personal, general),
    tax_id : "xx.xxx.xxx-xxx.xxx", // x is number digits I want the tax id to be formatted this way
    currency_code: "", // currency used in the book
};

ledger = {
    id : "", // combination of year month date and book id.
    date: new Date(), // date of the ledger posted
    book: user_code, // user code 
    user_name: book_data.user_name,
    accounts: [
        {
            account_id : 11001,
            account_name : "Kas dan Ekivalen", 
            account_type : "ASET", 
            account_subtype : "ASET LANCAR",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 11002,
            account_name : "Piutang Usaha", 
            account_type : "ASET", 
            account_subtype : "ASET LANCAR",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 11003,
            account_name : "Sekuritas Siap Jual", 
            account_type : "ASET", 
            account_subtype : "ASET LANCAR",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 11004,
            account_name : "Sekuritas Diperdagangkan", 
            account_type : "ASET", 
            account_subtype : "ASET LANCAR",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 11005,
            account_name : "Persediaan", 
            account_type : "ASET", 
            account_subtype : "ASET LANCAR",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 11006,
            account_name : "Beban Dibayar di Muka (Deferal)", 
            account_type : "ASET", 
            account_subtype : "ASET LANCAR",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 12001,
            account_name : "Sekuritas Hingga Jatuh Tempo", 
            account_type : "ASET", 
            account_subtype : "ASET TETAP",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 12002,
            account_name : "Piutang Jangka Panjang", 
            account_type : "ASET", 
            account_subtype : "ASET TETAP",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 12003,
            account_name : "Aset Jangka Panjang", 
            account_type : "ASET", 
            account_subtype : "ASET TETAP",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 12004,
            account_name : "less: Akumulasi Depresiasi", 
            account_type : "ASET", 
            account_subtype : "ASET TETAP",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 12005,
            account_name : "Aset Tidak Berwujud", 
            account_type : "ASET", 
            account_subtype : "ASET TETAP",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 12006,
            account_name : "less: Akumulasi Amortisasi", 
            account_type : "ASET", 
            account_subtype : "ASET TETAP",
            balance_side : "debit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 21001,
            account_name : "Hutang Usaha", 
            account_type : "KEWAJIBAN", 
            account_subtype : "KEWAJIBAN LANCAR",
            balance_side : "credit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 21002,
            account_name : "Deposit", 
            account_type : "KEWAJIBAN", 
            account_subtype : "KEWAJIBAN LANCAR",
            balance_side : "credit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 21003,
            account_name : "Pendapatan Belum Diakui (deferal)", 
            account_type : "KEWAJIBAN", 
            account_subtype : "KEWAJIBAN LANCAR",
            balance_side : "credit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 21004,
            account_name : "Hutang Pajak (akrual)", 
            account_type : "KEWAJIBAN", 
            account_subtype : "KEWAJIBAN LANCAR",
            balance_side : "credit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 22001,
            account_name : "Hutang Jangka Panjang", 
            account_type : "KEWAJIBAN", 
            account_subtype : "KEWAJIBAN JANGKA PANJANG",
            balance_side : "credit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 31001,
            account_name : "Modal Disetor", 
            account_type : "EKUITAS", 
            account_subtype : "EKUITAS PEMILIK",
            balance_side : "credit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 31002,
            account_name : "Laba/(Rugi) Sekuritas Siap Jual", 
            account_type : "EKUITAS", 
            account_subtype : "EKUITAS PEMILIK",
            balance_side : "credit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 31002,
            account_name : "Laba Ditahan", 
            account_type : "EKUITAS", 
            account_subtype : "EKUITAS PEMILIK",
            balance_side : "credit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 32001,
            account_name : "Bagian Minoritas", 
            account_type : "EKUITAS", 
            account_subtype : "KEPENTINGAN NON PENGENDALI",
            balance_side : "credit",
            closing_type : "permanent",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 41001,
            account_name : "Pendapatan Usaha", 
            account_type : "PENDAPATAN", 
            account_subtype : "PENDAPATAN OPERASIONAL",
            balance_side : "credit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 41002,
            account_name : "Laba/(Rugi) Sekuritas Diperdagangkan", 
            account_type : "PENDAPATAN", 
            account_subtype : "PENDAPATAN OPERASIONAL",
            balance_side : "credit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 41003,
            account_name : "Pendapatan Bunga dan Bagi Hasil", 
            account_type : "PENDAPATAN", 
            account_subtype : "PENDAPATAN OPERASIONAL",
            balance_side : "credit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 42001,
            account_name : "Pendapatan dari Transaksi", 
            account_type : "PENDAPATAN", 
            account_subtype : "PENDAPATAN LAIN-LAIN",
            balance_side : "credit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 42002,
            account_name : "Laba/(Rugi) dari Nilai Tukar", 
            account_type : "PENDAPATAN", 
            account_subtype : "PENDAPATAN LAIN-LAIN",
            balance_side : "credit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 42003,
            account_name : "Pendapatan Lain", 
            account_type : "PENDAPATAN", 
            account_subtype : "PENDAPATAN LAIN-LAIN",
            balance_side : "credit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 51001,
            account_name : "Harga Pokok Penjualan", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN OPERASIONAL",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 51002,
            account_name : "Beban Transaksi (Komisi)", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN OPERASIONAL",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 51003,
            account_name : "Pajak Pertambahan Nilai (non-Kredit)", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN OPERASIONAL",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 52001,
            account_name : "Beban Administrasi", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN LAIN-LAIN",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 52002,
            account_name : "Beban Perawatan", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN LAIN-LAIN",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 52003,
            account_name : "Beban Penyesuaian Deferal", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN LAIN-LAIN",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 52004,
            account_name : "Beban Gaji", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN LAIN-LAIN",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 52005,
            account_name : "Pajak Lain (non-Penghasilan)", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN LAIN-LAIN",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 52006,
            account_name : "Beban Lain", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN LAIN-LAIN",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 53001,
            account_name : "Beban Depresiasi", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN ASET TETAP",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 53002,
            account_name : "Beban Amortisasi", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN ASET TETAP",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 54001,
            account_name : "Beban Bunga", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN KEWAJIBAN",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 55001,
            account_name : "Pajak Penghasilan", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN PAJAK",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        },
        {
            account_id : 56001,
            account_name : "Deviden/Prive", 
            account_type : "BEBAN", 
            account_subtype : "BEBAN EKUITAS",
            balance_side : "debit",
            closing_type : "temporary",
            status : 'active',
            open_credit : 0,
            open_debit : 0,
            open_balance : 0,
            close_credit : 0,
            close_debit : 0,
            close_balance :0,
            tags : []
        }
    ]
}